name: Close Stale Issues

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs.'
          close-issue-message: 'Closing this issue due to prolonged inactivity.'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'pinned,security'
